#include "module2types.h"
BTtree BTcreate(int);
int BTHeight(BTtree);
void visit(BTtree, BTnode);
void BTPreOrder(BTtree, Visit);
void BTInOrder(BTtree, Visit);
void BTPostOrder(BTtree, Visit);
void BTLevelOrder(BTtree, Visit);
int BTIsEmpty(BTtree, BTnode);
int BTSize(BTtree);
BTnode BTGetRoot(BTtree);
BTnode BTGetParent(BTtree, BTnode);
BTnode BTGetChildLeft(BTtree, BTnode);
BTnode BTGetChildRight(BTtree, BTnode);
BTitem BTGetItem(BTtree, BTnode);
BTnode search(BTtree, BTnode);
void Destroy(BTtree);
void Remove(BTtree, BTnode);
BTtree insertroot(BTtree, BTitem);
void BTInsertLeft(BTtree, BTnode, BTitem);
void BTInsertRight(BTtree, BTnode, BTitem);
void BTChange(BTtree, BTnode, BTitem);
void printLevel(BTtree, int, Visit);
void preorder(BTtree, BTnode, Visit);
void inorder(BTtree, BTnode, Visit);
void postorder(BTtree , BTnode , Visit );
void Changeparen(BTtree *, BTtree);
void Changeright(BTtree *, BTtree);
void kill(BTtree tree, BTnode node);
void Changeleft(BTtree *, BTtree);
void BTChangeKey(BTtree, BTnode, BSTKeyType);
BSTKeyType BSTGetKey(BTtree, BTnode);
